name: Fetch Matches

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -e .

      - name: Run fetcher
        run: python -m soccer_matches.fetch

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -n "$(git status --porcelain data)" ]; then
            git add data
            git commit -m "Update match data"
            git push
          else
            echo "No changes to commit."
          fi
